### PR TITLE
FP1 Assignment 1

### PR DESCRIPTION
**Pull request by rajiaxoxo**

### CODE REVIEW

**Comment by marksherman** [comment]
Looks pretty good. I need the images _in_ the readme.md file, with each explained. 

Explanation of your story is good, and code highlights are well done.

**Comment by rajiaxoxo** [comment]
Sure, i'll add them!

**Comment by rajiaxoxo** [comment]
Hi Mark, I made the changes you asked for. Hope that's better! Let me know if you would like me to make anymore changes. 

Rajia

**Comment by marksherman** [comment]
Fantastic! Thank you.

**Pull request closed without merging**
