### PR TITLE
updated: finished part 1, experiment

### PR DESCRIPTION
**Pull request by alexcushing**
Had image inline and code added

### CODE REVIEW

**Comment by marksherman** [comment]
Why is your first paragraph in a block quotation? This is also your only exposition, which is on the shallow end.

Please fix and message back when done.

**Comment by alexcushing** [comment]
removed block quote and added more of an explanation to the code itself

**Comment by marksherman** [comment]
Not bad, right? Thank you. Good work.

**Comment by marksherman** [comment]
This is a duplicate of #24 .... why (and how) did you make two separate requests?

You ended up having two different conversations with @fgmart and myself. 

Only make one pull request per assignment.

**Comment by marksherman** [comment]
On further review, this is clearly the good one. Marking as complete and awarding the grade.

**Pull request closed without merging**
