### PR TITLE
Turtle Graphics

### PR DESCRIPTION
**Pull request by sberube484**

### CODE REVIEW

**Comment by marksherman** [comment]
This is really cool, and your choice of demonstration is beautiful and, dare I say, artistic.

Please put your name in the damn readme file.

**Comment by marksherman** [comment]
When changes are committed, message me back.

**Comment by sberube484** [comment]
Sorry about that! I just made the changes.

On Mar 20, 2016, at 9:23 PM, Mark Sherman <notifications@github.com<mailto:notifications@github.com>> wrote:

When changes are committed, message me back.

##

**Comment by fgmart-zz** [comment]
Nice work Sean.

**Pull request closed without merging**
