### PR TITLE
FP1

### PR DESCRIPTION
**Pull request by TheMeraCoder**
FP1 assignment, it has 3 files in it, the readme file, the soucefile named FP1 and the image file

### CODE REVIEW

**Comment by TheMeraCoder** [comment]
Honestly it kind of a pain to read the library descriptions and there isn't alot of examples in the documentations

**Comment by marksherman** [comment]
Very cool. yes, I know those docs can be a bit rough to read, especially when you haven't gotten used to the lingo yet. 

Please format your code snippet properly using the triple backticks. 

Message me back here @marksherman when you're done.

**Comment by TheMeraCoder** [comment]
@marksherman What do you mean by triple back ticks?  And is it in the rkr file I need to formart or the Readme file?

**Comment by marksherman** [comment]
That's it! It was just the formatting in the readme file. Your code, and your actual work, has been good this whole time! all set now. :100:

**Comment by TheMeraCoder** [comment]
Thank you
From,
Aliyu Zakari
UMS# 01190914

On Mar 21, 2016, at 22:24, Mark Sherman <notifications@github.com<mailto:notifications@github.com>> wrote:

That's it! It was just the formatting in the readme file. Your code, and your actual work, has been good this whole time! all set now. [:100:]

**Pull request closed without merging**
