### PR TITLE
Yusuf Yildiz Resubmission

### PR DESCRIPTION
**Pull request by yyildiz**

### CODE REVIEW

**Comment by marksherman** [comment]
You used the incorrect quote symbol to format your code. The result is it isn't formatted like code. Was that not obvious looking at it? Because it wasn't code, the regexp accidentally triggered the bold markdown for the rest of your writing, which is also incorrect.

`'''#rx"((?=<strong>Meeting).*?(?<=</ul>))'''`

Please correct and message back.

**Comment by yyildiz** [comment]
I just fixed it

**Comment by marksherman** [comment]
@yyildiz, please stop making multiple pull requests. We want the whole conversation to be in one place. 
Additionally, you've probably noticed that it's actually a pain in the ass to make more than one PR per repo. That's a sign that you might be doing your process wrong. 

Each repo should have at most ONE pull request from you. Changes should be made to that same branch as we explore.

Now this one looks basically complete, but because it's had an interesting history so far, I want @fgmart to check it before it gets marked as complete.

I'm leaving it open for now.

**Comment by fgmart-zz** [comment]
ok

**Pull request closed without merging**
