### PR TITLE
Laura_LucaciuOPL2016_FP1

### PR DESCRIPTION
**Pull request by LauraLucaciu**

### CODE REVIEW

**Comment by marksherman** [comment]
This is incomplete. The instructions included:

> Remember that this report must include:
> - a narrative of what you did
> - highlights of code that you wrote, with explanation
> - output from your code demonstrating what it produced
> - at least one diagram or figure showing your work
> 
> The narrative itself should be no longer than 350 words. Yes, you need at least one image (output, diagrams). Images must be embedded into this md file. We should not have to click a link to see it. 

Please revise and message back when complete.

**Comment by LauraLucaciu** [comment]
Thank you for letting me know.

As soon as get home from work I will revise and send a message.

Regards,

Laura Lucaciu 

From: Mark Sherman

Sent: Monday, March 21, 9:50 PM

Subject: Re: [FP1] Laura_LucaciuOPL2016_FP1 (#43)

To: oplS16projects/FP1

Cc: LauraLucaciu

This is incomplete. The instructions included:

Remember that this report must include:

a narrative of what you didhighlights of code that you wrote, with explanationoutput from your code demonstrating what it producedat least one diagram or figure showing your work 

The narrative itself should be no longer than 350 words. Yes, you need at least one image (output, diagrams). Images must be embedded into this md file. We should not have to click a link to see it. 

Please revise and message back when complete.

**Comment by LauraLucaciu** [comment]
Hi,

I just revised FP1 and added also images embedded into the md file.

Thank you.

Laura Lucaciu

From: Mark Sherman
Sent: ‎Monday‎, ‎March‎ ‎21‎, ‎2016 ‎9‎:‎50‎ ‎PM
To: oplS16projects/FP1
Cc: LauraLucaciu

This is incomplete. The instructions included:

Remember that this report must include:
a narrative of what you did
highlights of code that you wrote, with explanation
output from your code demonstrating what it produced
at least one diagram or figure showing your work

The narrative itself should be no longer than 350 words. Yes, you need at least one image (output, diagrams). Images must be embedded into this md file. We should not have to click a link to see it. 

Please revise and message back when complete.

**Comment by marksherman** [comment]
and the end result is beautiful! Thank you. Good job.

**Pull request closed without merging**
