### PR TITLE
FP1 PR

### PR DESCRIPTION
**Pull request by sv-uml**

### CODE REVIEW

**Comment by marksherman** [comment]
Your "for example" section should be formatted properly. hard to tell what you're conveying. If it's code, or terminal, make it look like it. Commit changes and ping me here @marksherman when you're ready.

**Comment by sv-uml** [comment]
@marksherman Made the changes!

**Comment by marksherman** [comment]
@sv-uml , please delete the instructions from your file. Only include your contents. This is a report.

Also, ensure that any diagrams you did not make yourself are properly cited.

**Comment by sv-uml** [comment]
@marksherman I have made the necessary changes.

**Comment by marksherman** [comment]
:clap: :100:

**Pull request closed without merging**
