### PR TITLE
Initial Part of Final Project

### PR DESCRIPTION
**Pull request by eampadu**
Includes source code and README.md

### CODE REVIEW

**Comment by marksherman** [comment]
You are missing these three requirements:
- highlights of code that you wrote, with explanation
- output from your code demonstrating what it produced
- at least one diagram or figure showing your work

**Comment by eampadu** [comment]
Dear Professor Sherman:

I spoke with Professor Martin in class today regarding the missing files, and he explained what happened:

I submitted the work before the deadline, but did not include my name on your list. He advised me to email you to take another look, using my username of "eampadu," while I fix the issue in Github.

Thank you for your consideration.

Sincerely,

Ebenezer Ampadu

**Comment by marksherman** [comment]
@fgmart this still does not fulfill requirements of formatted code excerpts with explanation, and does not have an embedded image. 

Fred has given the point, so this should be marked as complete, but it still does not look complete to me.

I'm leaving this open so we can discuss.

**Comment by marksherman** [comment]
@eampadu This is still incomplete. You do not yet have formatted code highlights with explanation, and you do not yet have an embedded image. Please update ASAP.

cc @fgmart

**Comment by eampadu** [comment]
@fgmart :Just updated the readme.md for FP1 and embedded an image as requested.
@marksherman

**Comment by marksherman** [comment]
There we go! You did not have to make a second pull request. What you did here, on the same branch, was correct.

**Pull request closed without merging**
