### PR TITLE
HTML-Template

### PR DESCRIPTION
**Pull request by OhBehive**

### CODE REVIEW

**Comment by fgmart-zz** [comment]
Behailu -- you're missing an image file and the full code. Please update.

**Comment by OhBehive** [comment]
Added the image file and the code into a separate file. Forgot to change linkage in image file from last time which is why it didn't work.

**Comment by marksherman** [comment]
README.md must be named exactly that, or else it doesn't show up on the repository's home page. Please change it back. That file has special powers on github.

**Comment by OhBehive** [comment]
Whoops. Fixed!

**Comment by marksherman** [comment]
Good! Keeping the project schedule at the bottom isn't strictly necessary, but the rest is totally good. :clap:

**Pull request closed without merging**
