### PR TITLE
Christian Everett FP1

### PR DESCRIPTION
**Pull request by ChristianEverett**

### CODE REVIEW

**Comment by marksherman** [comment]
Requires one image embedded and the source code to be added to the repository.

The readme document could be cleaned up better, too.

Please make the changes and then comment to let us know it's ready to look at again.

**Comment by ChristianEverett** [comment]
I Received a message that I was missing an image and source code but they are both in the repo are you not able to see them?

**Comment by marksherman** [comment]
My mistake! I was looking at an older version. It struck me as a rough
draft, and that was why.

**Comment by marksherman** [comment]
Sorry I forgot to finish this! Looks great. keep it up.

**Comment by fgmart-zz** [comment]
Christian - did you make that diagram yourself? If not, you have to cite where you got it from. Please update.

**Comment by marksherman** [comment]
Re-opening awaiting citation

**Comment by ChristianEverett** [comment]
citation added

**Comment by marksherman** [comment]
citation looks good.

**Pull request closed without merging**
