### PR TITLE
YusufM_FirstProject

### PR DESCRIPTION
**Pull request by YusufSM**
Simple-qr

### CODE REVIEW

**Comment by marksherman** [comment]
Remember that this report must include:
- a narrative of what you did, about 350 words
- highlights of code that you wrote, formatted as code, with explanation
- output from your code demonstrating what it produced
- at least one diagram or figure showing your work

Your explanation is currently very short, and there are no images linked into the README file. Please complete, and then message back here when ready. You do not need a new pull request, simply commit changes to this branch.

**Comment by YusufSM** [comment]
I have updated my README file. I wasn't to sure how to link the picture, so I just wrote the link to where the pictures are in github in my README file.

**Comment by YusufSM** [comment]
Hi Professor Sherman,

I manage to put some pictures in my README file and copy part of my code into the README file. Right now, I'm struggling to find out how to do make a gray box in my README file to put my code in so that it looks neater. Also, for my second project, after I create a pull request, I am not sure how I can upload pictures. Sorry I am very new to github.

Thanks for your patience,

Yusuf

**Comment by marksherman** [comment]
It looks like you largely figured it out. For the future, in the original instructions, you'll find this link explaining markdown: https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/

Your description of what you did is still a little short. For FP2 ensure that you _completely_ explain what you did. if it's under 100 words, either you didn't explain it thoroughly, or you didn't do enough!

This is acceptable, but please use this feedback to improve your future work.

**Pull request closed without merging**
