### PR TITLE
Michael Antrobus FP1

### PR DESCRIPTION
**Pull request by Aurelas**
Here it is!

### CODE REVIEW

**Comment by marksherman** [comment]
Please proofread for grammar and spelling.
Please fix your image. It is currently a broken link. The image can be added to the repo itself, and easily referenced from the readme file. 

Let me know when it is complete.

**Comment by Aurelas** [comment]
Since i can see the changes i'm doing above i believe i don't have to ask for another PR so i believe i fixed everything.

**Comment by marksherman** [comment]
Images still don't work.
screen shot 2016-03-24 at 9 25 13 am

**Comment by Aurelas** [comment]
/fingers crossed third times the charm, i also added more code and explanations

**Comment by marksherman** [comment]
Indeed!

**Pull request closed without merging**
