### PR TITLE
Final Project Assignment 1: Exploration (FP1)

### PR DESCRIPTION
**Pull request by mkhalid578**
Name: Muhammed Khalid
Date: 03/08/2016
Section: Fred G. Martin (MWF 12-12:50 pm)

### CODE REVIEW

**Comment by marksherman** [comment]
Nice.

**Comment by fgmart-zz** [comment]
You need to put your name in the MD file! Please update!!

Other than this -- beautiful.

**Comment by mkhalid578** [comment]
Professor Martin, 

I believe I made the changes.

**Comment by fgmart-zz** [comment]
thanks.

**Pull request closed without merging**
